theme = "Catppuccin-mocha"
client_id = "1adcca86e8f344a4ae67c409290edcea"
client_port = 8080
playback_format = """
{track} • {artists}
{album}







{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Rounded"
progress_bar_type = "Line"
playback_window_position = "Top"
cover_img_length = 22
cover_img_width = 10
cover_img_scale = 1.0
playback_window_width = 10
enable_media_control = true
enable_streaming = "DaemonOnly"
enable_notify = true
enable_cover_image_cache = true
default_device = "spotify-daemon"
notify_streaming_only = true

[copy_command]
command = "wl-copy"
args = [
]

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[device]
name = "spotify-daemon"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
