#!/bin/sh

COMPLETED_DIR="$HOME/Downloads/"
DOWNLOADING_DIR="$HOME/Downloads/.downloading/"

FILE="$(basename "$3")"
FINAL="$COMPLETED_DIR/$FILE"
mv "$3" "$FINAL"

LOG_FILE="$HOME/Downloads/.downloading/downloads.json"
TEMP_FILE="$(mktemp)"

jq --arg name "$FILE" 'del(.[] | select(.name == $name))' "$LOG_FILE" > "$TEMP_FILE"
mv "$TEMP_FILE" "$LOG_FILE"

COUNT="$(jq '. | length' "$LOG_FILE")"
if [ "$COUNT" -eq 0 ]; then
    rm -r "$DOWNLOADING_DIR"
fi

"$HOME"/.config/aria2/notification "$FINAL" &
