#!/bin/sh

COMPLETED_DIR="$HOME/Downloads/"
DOWNLOADING_DIR="$HOME/Downloads/.downloading/"

mv "$3" "$COMPLETED_DIR/$(basename "$3")"

COUNT="$(ls -1 "$DOWNLOADING_DIR" | wc -l)"
if [ "$COUNT" -eq 0 ]; then
    rm -r "$DOWNLOADING_DIR"
fi

"$HOME"/.config/aria2/notification "$3" &
