#!/bin/sh

ACTION="$(notify-send -i emblem-checked "Download Complete" "$(basename "$1")" -A "opendir=Open Downloads Folder" -A "open=Open File")"

case "$ACTION" in
    opendir)
        xdg-open "$(dirname "$1")"
        ;;
    open)
        xdg-open "$1"
esac
