require('colorscheme').add_groups(function(C)
    return {
        ColorColumn = { bg = C.bg0  },
        Conceal = { fg = C.fg1 },
        CurSearch = { fg = C.black, bg = C.yellow },
        Cursor = { fg = C.black, bg = C.fg0 },
        lCursor = { link = 'Cursor' },
        CursorIM = { link = 'Cursor' },
        CursorColumn = { link = 'CursorLine' },
        CursorLine = { bg = C.bg1 },
        Directory = { fg = C.blue },
        DiffAdd = { fg = C.black, bg = C.green },
        DiffChange = { fg = C.black, bg = C.yellow },
        DiffDelete = { fg = C.black, bg = C.red },
        DiffText = { fg = C.black, bg = C.yellow, bold = true, italic = true },
        DiffTextAdd = { fg = C.black, bg = C.green, bold = true, italic = true },
        EndOfBuffer = { link = 'Conceal' },
        TermCursor = { link = 'Cursor' },
        OkMsg = { fg = C.green },
        WarningMsg = { fg = C.yellow },
        ErrorMsg = { fg = C.red },
        StderrMsg = { link = 'ErrorMsg' },
        StdoutMsg = { link = 'Normal' },
        WinSeparator = { link = 'Normal' },
        Folded = { fg = C.fg1, bg = C.bg1 },
        FoldColumn = { link = 'Conceal' },
        SignColumn = { link = 'Conceal' },
        IncSearch = { link = 'Substitute' },
        Substitute = { fg = C.black, bg = C.yellow, bold = true },
        LineNr = { fg = C.fg0, bold = true },
        LineNrAbove = { fg = C.fg1 },
        LineNrBelow = { fg = C.fg1 },
        CursorLineNr = { link = 'LineNr' },
        CursorLineFold = { link = 'FoldColumn' },
        CursorLineSign = { link = 'SignColumn' },
        -- MatchParen,
        ModeMsg = { fg = C.green },
        MsgArea = { link = 'Normal' },
        -- MsgSeparator,
        MoreMsg = { fg = C.cyan },
        NonText = { fg = C.fg1 },
        Normal = { fg = C.fg0, bg = C.bg0 },
        -- NormalFloat,
        -- FloatBorder,
        -- FloatShadow,
        -- FloatShadowThrough,
        -- FloatTitle,
        -- FloatFooter,
        -- NormalNC,
        -- Pmenu,
        -- PmenuSel,
        -- PmenuKind,
        -- PmenuKindSel,
        -- PmenuExtra,
        -- PmenuExtraSel,
        -- PmenuSbar,
        -- PmenuThumb,
        -- PmenuMatch,
        -- PmenuMatchSel,
        -- PmenuBorder,
        -- PmenuShadow,
        -- PmenuShadowThrough,
        -- ComplMatchIns,
        -- PreInsert,
        -- ComplHint,
        -- ComplHintMore,
        -- Question,
        -- QuickFixLine,
        -- Search,
        -- SnippetTabstop,
        -- SnippetTabstopActive,
        -- SpecialKey,
        SpellBad = { fg = C.fg0, sp = C.red, undercurl = true },
        SpellCap = { fg = C.fg0, sp = C.yellow, undercurl = true },
        SpellLocal = { fg = C.fg0, sp = C.green, undercurl = true },
        SpellRare = { fg = C.fg0, sp = C.cyan, undercurl = true },
        StatusLine = { bg = C.bg1 },
        StatusLineNC = { bg = C.fg1 }, -- FIXME: determine better way to handle this
        StatusLineTerm = { link = 'StatusLine' },
        StatusLineTermNC = { link = 'StatusLineNC' },
        TabLine = { fg = C.fg1, bg = C.bg1 },
        TabLineFill = { bg = C.bg0 },
        TabLineSel = { fg = C.black, bg = C.blue },
        -- Title,
        Visual = { bg = C.bg1, bold = true },
        VisualNOS = { link = 'Visual' },
        Whitespace = { fg = C.red },
        -- WildMenu,
        -- WinBar,
        -- WinBarNC,
    }
end)
