require('colorscheme').add_groups(function(C)
    return {
        Comment = { fg = C.fg1 },
        Constant = { fg = C.purple },
        String = { fg = C.green },
        Character = { link = 'String' },
        Number = { link = 'Constant' },
        Boolean = { fg = C.orange },
        Float = { link = 'Constant' },
        Identifier = { fg = C.fg0 },
        Function = { fg = C.blue },
        Statement = { fg = C.purple },
        Conditional = { link = 'Statement' },
        Repeat = { link = 'Statement' },
        Label = { link = 'Statement' },
        Operator = { fg = C.orange },
        Keyword = { link = 'Statement' },
        Exception = { link = 'Statement' },
        PreProc = { fg = C.purple },
        Include = { link = 'PreProc' },
        Define = { link = 'PreProc' },
        Macro = { link = 'PreProc' },
        PreCondit = { link = 'PreProc' },
        Type = { fg = C.yellow, bold = true },
        StorageClass = { link = 'Type' },
        Structure = { link = 'Type' },
        Typedef = { link = 'Type' },
        Special = { fg = C.cyan },
        SpecialChar = { link = 'Special' },
        Tag = { link = 'Special' },
        Delimiter = { link = 'Special' },
        SpecialComment = { link = 'Special' },
        Debug = { link = 'Special' },
        Underlined = { fg = C.fg0, underline = true },
        Ignore = { link = 'Normal' },
        Error = { link = 'ErrorMsg' },
        Todo = { fg = C.cyan, bold = true },
        Added = { link = 'DiffAdd' },
        Changed = { link = 'DiffChange' },
        Removed = { link = 'DiffDelete' },
    }
end)
