require('colorscheme').add_groups(function(C)
    return {
        ['@variable'] = { fg = C.fg0 },
        ['@variable.builtin'] = { fg = C.red },
        ['@variable.parameter'] = { fg = C.red },
        ['@variable.parameter.builtin'] = { fg = C.red },
        ['@variable.member'] = { fg = C.fg0 },
        ['@constant'] = { link = 'Constant' },
        ['@constant.builtin'] = { link = '@constant' },
        ['@constant.macro'] = { link = '@constant' },
        ['@module'] = { fg = C.yellow, bold = true },
        ['@module.builtin'] = { link = '@module' },
        ['@label'] = { link = 'Keyword' },
        ['@string'] = { link = 'String' },
        ['@string.documentation'] = { link = '@string' },
        ['@string.regexp'] = { link = '@string.special' },
        ['@string.escape'] = { link = '@string.special' },
        ['@string.special'] = { fg = C.orange },
        ['@string.special.symbol'] = { link = '@string.special' },
        ['@string.special.path'] = { link = '@string.special' },
        ['@string.special.url'] = { fg = C.green, underline = true },
        ['@character'] = { link = 'Character' },
        ['@character.special'] = { fg = C.orange },
        ['@boolean'] = { link = 'Boolean' },
        ['@number'] = { link = 'Number' },
        ['@number.float'] = { link = 'Float' },
        ['@type'] = { link = 'Type' },
        ['@type.builtin'] = { link = '@type' },
        ['@type.definition'] = { link = '@type' },
        ['@attribute'] = { link = 'Statement' },
        ['@attribute.builtin'] = { link = '@attribute' },
        ['@property'] = { fg = C.fg0 },
        ['@function'] = { link = 'Function' },
        ['@function.builtin'] = { link = '@function' },
        ['@function.call'] = { link = '@function' },
        ['@function.macro'] = { link = '@function' },
        ['@function.method'] = { link = '@function' },
        ['@function.method.call'] = { link = '@function' },
        ['@constructor'] = { link = '@function' },
        ['@operator'] = { link = 'Operator' },
        ['@keyword'] = { link = 'Keyword' },
        ['@keyword.coroutine'] = { link = '@keyword' },
        ['@keyword.function'] = { link = '@keyword' },
        ['@keyword.operator'] = { link = 'Operator' },
        ['@keyword.import'] = { link = 'Include' },
        ['@keyword.type'] = { link = '@keyword' },
        ['@keyword.modifier'] = { link = 'StorageClass' },
        ['@keyword.repeat'] = { link = 'Repeat' },
        ['@keyword.return'] = { link = '@keyword' },
        ['@keyword.debug'] = { link = '@keyword' },
        ['@keyword.exception'] = { link = 'Exception' },
        ['@keyword.conditional'] = { link = 'Conditional' },
        ['@keyword.conditional.ternary'] = { link = '@keyword.conditional' },
        ['@keyword.directive'] = { link = 'PreProc' },
        ['@keyword.directive.define'] = { link = 'Define' },
        ['@punctuation.delimiter'] = { fg = C.fg0 },
        ['@punctuation.bracket'] = { fg = C.fg0 },
        ['@punctuation.special'] = { fg = C.fg0 },
        ['@comment'] = { fg = C.fg1 },
        ['@comment.documentation'] = { fg = C.fg1 },
        ['@comment.error'] = { fg = C.red, bold = true },
        ['@comment.warning'] = { fg = C.yellow, bold = true },
        ['@comment.todo'] = { fg = C.cyan, bold = true },
        ['@comment.note'] = { fg = C.blue, bold = true },
        ['@markup.strong'] = { fg = C.purple, bold = true },
        ['@markup.italic'] = { fg = C.green, italic = true },
        ['@markup.strikethrough'] = { fg = C.red, strikethrough = true },
        ['@markup.underline'] = { fg = C.yellow, underline = true },
        ['@markup.heading'] = { bold = true },
        ['@markup.heading.1'] = { fg = C.red, bold = true },
        ['@markup.heading.2'] = { fg = C.orange, bold = true },
        ['@markup.heading.3'] = { fg = C.yellow, bold = true },
        ['@markup.heading.4'] = { fg = C.green, bold = true },
        ['@markup.heading.5'] = { fg = C.blue, bold = true },
        ['@markup.heading.6'] = { fg = C.purple, bold = true },
        ['@markup.quote'] = { fg = C.cyan },
        ['@markup.math'] = { fg = C.cyan },
        ['@markup.link'] = { underline = true },
        ['@markup.link.label'] = { link = '@markup.link' },
        ['@markup.link.url'] = { link = '@markup.link' },
        ['@markup.raw'] = { link = '@markup.quote' },
        ['@markup.raw.block'] = { link = '@markup.raw' },
        ['@markup.list'] = { fg = C.orange },
        ['@markup.list.checked'] = { fg = C.green },
        ['@markup.list.unchecked'] = { fg = C.fg0 },
        ['@diff.plus'] = { fg = C.black, bg = C.green },
        ['@diff.minus'] = { fg = C.black, bg = C.red },
        ['@diff.delta'] = { fg = C.black, bg = C.yellow },
        ['@tag'] = { fg = C.cyan },
        ['@tag.builtin'] = { link = '@tag' },
        ['@tag.attribute'] = { link = '@tag' },
        ['@tag.delimiter'] = { link = '@tag' },
    }
end)
