[manager]
keymap = [
    { on = [ "<Esc>" ], run = "escape",  desc = "Exit visual mode, clear selected, or cancel search" },
    { on = [ "q" ],     run = "quit",    desc = "Exit the process" },
    { on = [ "<C-z>" ], run = "suspend", desc = "Suspend the process" },

    # movement
    { on = [ "h" ], run = "leave",                     desc = "Leave the current directory and into its parent" },
    { on = [ "j" ], run = "arrow 1",                   desc = "Move the cursor down" },
    { on = [ "k" ], run = "arrow -1",                  desc = "Move the cursor up" },
    { on = [ "l" ], run = "plugin --sync smart-enter", desc = "Enter hovered directory, or open the file" },

    { on = [ "<C-u>" ], run = "arrow -50%",  desc = "Move cursor up half a page" },
    { on = [ "<C-d>" ], run = "arrow 50%",   desc = "Move cursor down half a page" },
    { on = [ "<C-b>" ], run = "arrow -100%", desc = "Move cursor up a page" },
    { on = [ "<C-f>" ], run = "arrow 100%",  desc = "Move cursor down a page" },

    { on = [ "J" ], run = "plugin --sync parent-arrow --args=1",  desc = "Move the cursor down in the previous panel" },
    { on = [ "K" ], run = "plugin --sync parent-arrow --args=-1", desc = "Move the cursor up in the previous panel" },

    { on = [ "g", "g" ], run = "arrow -99999999", desc = "Move cursor to the top" },
    { on = [ "G" ],      run = "arrow 99999999",  desc = "Move cursor to the bottom" },

    # move in preview
    { on = [ "<A-k>" ], run = "seek -5", desc = "Seek up 5 units in the preview" },
    { on = [ "<A-j>" ], run = "seek 5",  desc = "Seek down 5 units in the preview" },

    # goto
    { on = [ "g", "h" ],       run = "cd ~",           desc = "Go to the home directory" },
	{ on = [ "g", "c" ],       run = "cd ~/.config",   desc = "Go to the config directory" },
	{ on = [ "g", "d" ],       run = "cd ~/Downloads", desc = "Go to the downloads directory" },
	{ on = [ "g", "t" ],       run = "cd /tmp",        desc = "Go to the temporary directory" },
	{ on = [ "g", "/" ],       run = "cd /",           desc = "Go to the root directory" },

    # selection
    { on = [ "<Space>" ], run = [ "select --state=none", "arrow 1" ], desc = "Toggle the current selection state" },
    { on = [ "v" ],       run = "visual_mode",                        desc = "Enter visual mode (selection mode)" },
    { on = [ "V" ],       run = "visual_mode --unset",                desc = "Enter visual mode (unset mode)" },
    { on = [ "<C-a>" ],   run = "select_all --state=true",            desc = "Select all files" },
    { on = [ "<C-r>" ],   run = "select_all --state=none",            desc = "Inverse selection of all files" },
    { on = [ "u" ],       run = "select_all --state=false",           desc = "Deselect all files" },

    # copy/cut/pase
    { on = [ "y" ], run = "yank",       desc = "Copy the selected files" },
    { on = [ "d" ], run = "yank --cut", desc = "Cut the selected files" },
    { on = [ "c" ], run = "unyank",     desc = "Cancel the yank status of files" },
    { on = [ "p" ], run = "paste",      desc = "Paste the files" },

    # trash/delete
    { on = [ "<Backspace>" ],   run = "remove",               desc = "Trash file" },
    { on = [ "<S-Backspace>" ], run = "remove --permanently", desc = "Delete file" },

    # linemode
    { on = [ "m", "s" ], run = "linemode size",        desc = "Set linemode to size" },
	{ on = [ "m", "p" ], run = "linemode permissions", desc = "Set linemode to permissions" },
	{ on = [ "m", "m" ], run = "linemode mtime",       desc = "Set linemode to mtime" },
	{ on = [ "m", "n" ], run = "linemode none",        desc = "Set linemode to none" },
	{ on = [ "m", "t" ], run = "linemode tags",        desc = "Set linemode to tags" },

    # misc
    { on = [ "o" ],      run = "open",                               desc = "Open the selected files" },
	{ on = [ "O" ],      run = "open --interactive",                 desc = "Open the selected files interactively" },
	{ on = [ ";" ],      run = "shell --interactive",                desc = "Run a shell command" },
	{ on = [ ":" ],      run = "shell --block --interactive",        desc = "Run a shell command (block the UI until the command finishes)" },
    { on = [ "a" ],      run = "create",                             desc = "Create a file or directory" },
    { on = [ "r" ],      run = "rename --cursor=before_ext",         desc = "Rename a file or directory" },
    { on = [ "R" ],      run = "rename --cursor=start --empty=stem", desc = "Rename a file or directory (clear filename)" },
    { on = [ "." ],      run = "hidden toggle",                      desc = "Toggle the visibility of hidden files" },
    { on = [ "i" ],      run = "plugin --sync max-preview",          desc = "Toggle maximized preview" },
    { on = [ "z", "p" ], run = "plugin --sync hide-preview",         desc = "Toggle preview" },

    # search
    { on = [ "f" ], run = "filter --smart",        desc = "Filter the files" },
    { on = [ "/" ], run = "find --smart",          desc = "Find next file" },
    { on = [ "n" ], run = "find_arrow",            desc = "Go to next found file" },
    { on = [ "N" ], run = "find_arrow --previous", desc = "Go to previous found file" },
    { on = [ "F" ], run = "search fd",             desc = "Search files by name using fd" },

    # sort
    { on = [ "s", "m" ], run = ["sort modified --reverse=no --dir-first", "plugin --sync smart-sort"],      desc = "Sort by modified time" },
	{ on = [ "s", "M" ], run = ["sort modified --reverse=yes --dir-first", "plugin --sync smart-sort"],     desc = "Sort by modified time (reverse)" },
	{ on = [ "s", "c" ], run = ["sort created --reverse=no --dir-first", "plugin --sync smart-sort"],       desc = "Sort by created time" },
	{ on = [ "s", "C" ], run = ["sort created --reverse=yes --dir-first", "plugin --sync smart-sort"],      desc = "Sort by created time (reverse)" },
	{ on = [ "s", "e" ], run = ["sort extension --reverse=no --dir-first", "plugin --sync smart-sort"],     desc = "Sort by extension" },
	{ on = [ "s", "E" ], run = ["sort extension --reverse=yes --dir-first", "plugin --sync smart-sort"],    desc = "Sort by extension (reverse)" },
	{ on = [ "s", "a" ], run = ["sort alphabetical --reverse=no --dir-first", "plugin --sync smart-sort"],  desc = "Sort alphabetically" },
	{ on = [ "s", "A" ], run = ["sort alphabetical --reverse=yes --dir-first", "plugin --sync smart-sort"], desc = "Sort alphabetically (reverse)" },
	{ on = [ "s", "n" ], run = ["sort natural --reverse=no --dir-first", "plugin --sync smart-sort"],       desc = "Sort naturally" },
	{ on = [ "s", "N" ], run = ["sort natural --reverse=yes --dir-first", "plugin --sync smart-sort"],      desc = "Sort naturally (reverse)" },
	{ on = [ "s", "s" ], run = ["sort size --reverse=no --dir-first", "plugin --sync smart-sort"],          desc = "Sort by size" },
	{ on = [ "s", "S" ], run = ["sort size --reverse=yes --dir-first", "plugin --sync smart-sort"],         desc = "Sort by size (reverse)" },

    # menus
    { on = [ "?" ], run = "help",       desc = "Open help menu" },
    { on = [ "w" ], run = "tasks_show", desc = "Open tasks menu" },

    { on = [ "t", "a" ], run = "plugin --sync taggy --args=add", desc = "Add tag" },
    { on = [ "t", "t" ], run = "plugin --sync taggy --args=tag", desc = "Tag file" },
]


[tasks]
keymap = [
    { on = [ "<Esc>" ], run = "close",  desc = "Hide the task manager" },
    { on = [ "q" ],     run = "close",  desc = "Hide the task manager" },
    { on = [ "w" ],     run = "close",  desc = "Hide the task manager" },

    { on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },

    { on = [ "<Enter>" ], run = "inspect", desc = "Inspect the task" },
    { on = [ "x" ],       run = "cancel",  desc = "Cancel the task" },

    { on = [ "?" ], run = "help", desc = "Open help menu" },
]

[select]
keymap = [
    { on = [ "<Esc>" ],   run = "close",          desc = "Cancel selection" },
    { on = [ "<Enter>" ], run = "close --submit", desc = "Submit selection" },

    { on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },

    { on = [ "?" ], run = "help", desc = "Open help menu" },
]

[help]
keymap = [
    { on = [ "<Esc>" ], run = "escape", desc = "Clear the filter, or hide the help" },
    { on = [ "q" ],     run = "close",  desc = "Hide the help" },
    { on = [ "?" ],     run = "close",  desc = "Hide the help" },

    { on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },

    { on = [ "/" ], run = "filter", desc = "Apply a filter for the help items" },
]
