#!/bin/bash

alias ls="eza -l --no-quotes --group-directories-first"
alias la="eza -la --no-quotes --group-directories-first"
alias :q="exit"
alias bash="HISTFILE=/dev/null bash"

alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
