#!/bin/sh
source "$ZDOTDIR/zsh-functions"

zsh_add_file "zsh-exports"

unsetopt BEEP
setopt autocd menucomplete
stty stop undef
zle_highlight=('paste:none')
autoload -Uz add-zsh-hook

# history
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="$XDG_CACHE_HOME/zsh/history"
mkdir -p "$XDG_CACHE_HOME/zsh"

# completions
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit


zsh_add_plugin "zsh-users/zsh-autosuggestions"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
zsh_add_plugin "zdharma-continuum/fast-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"

zsh_add_file "zsh-aliases"
zsh_add_file "zsh-prompt"
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-fzf"
zsh_add_file "zsh-keybinds"


ascii

autopair-init
